### ISSUE TITLE
can't compile - HAS_MEM_FUNC missing

### ISSUE THREAD

**Issue by robromano** [wichtounet/budgetwarrior#10]
https://github.com/sitmo/stdfin seems to provide this, is this a new dependency?

**Comment by wichtounet** [comment]
Hi, 

No, stdfin is not a dependency. HAS_MEM_FUNC is defined into cpp_utils, a submodule. 

Can you try initializing the submodules: `git submodule update --init --recursive` and compile again?

If this does not work, please tell me which compiler you are using and the command you are using to compile. 

Baptiste

**Comment by robromano** [comment]
I did try git submodule update --init --recursive  but maybe what is happening is from my fork of your repo, it is stuck at the older version. I fast forwarded and pulled in all your changes since my fork (after I added MacOS build support) so I thought it would also have pulled in the latest cpp_utils for me. In fact, I updated cpp-httplib as well to fix errors and it worked.

**Comment by wichtounet** [comment]
Hi, 

It is possible that the submodules are out of sync in your fork. But I have not updated cpp_utils is a while and this is a really old macro. 

At least it's working :)

**Comment by robromano** [comment]
Thanks, it worked.  I reran cmake and updated it’s cache and problem went
away
