### ISSUE TITLE
 Compile error:  src/pages/accounts_pages.cpp

### ISSUE THREAD

**Issue by ezorfa** [wichtounet/budgetwarrior#11]
Hi @wichtounet !

I am compiling on MacOS as way you have suggested. I get this error:
```
-e [release_debug] Compile src/pages/accounts_pages.cpp
error: unable to open output file
      'release_debug/src/pages/accounts_pages.cpp.o':
      'No such file or directory'
1 error generated.
make: *** [release_debug/src/pages/accounts_pages.cpp.o] Error 1
```
Could you please help me with this?

**Comment by wichtounet** [comment]
Hi, 

Sorry for the delay, I was in holidays. 

What command did you use to compile budgetwarrior? And in which folder are you?

**Comment by ezorfa** [comment]
HI @wichtounet ! Thankyou for your response!

I used the same set of command as mentioned on the Readme page:
`$ git clone --recursive git://github.com/wichtounet/budgetwarrior.git
$ cd budgetwarrior
$ ./build_macos.sh
$ make`


Also, When I check the gcc version by the command gcc --version, I get this: 
`Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

**Comment by wichtounet** [comment]
Maybe @robromano could help?

**Comment by robromano** [comment]
you need to cd into the build directory and run make
i.e.
```
$ git clone --recursive git://github.com/wichtounet/budgetwarrior.git 
$ cd budgetwarrior 
$ ./build_macos.sh 
$ cd build
$ make
```

I will submit a PR to fix the documentation.

**Comment by ezorfa** [comment]
Hi @robromano @wichtounet !
Thankyou ! Once I build it successfully, I am not able to launch the application. 'budget' is not found `zsh: command not found: budget` error. I am executing the command from budgetwarrior folder.

**Comment by thepoorswiss** [comment]
Did you do `sudo make install` ?

**Comment by ezorfa** [comment]
Hi @thepoorswiss !

I tried to do `sudo make install` in folder budgetwarrior and I get this error :
`-e [release_debug] Compile src/pages/accounts_pages.cpp
error: unable to open output file
      'release_debug/src/pages/accounts_pages.cpp.o':
      'No such file or directory'
1 error generated.
make: *** [release_debug/src/pages/accounts_pages.cpp.o] Error 1`

and When I do the same in build directory, I get the following error:

`make: *** No rule to make target `install'.  Stop.`

Thankyou

**Comment by thepoorswiss** [comment]
I am guessing that the make install script has not been updated for Mac yet. 

Can you try (in budgetwarrior directory):

`./build/release_debug/bin/budget`

**Comment by ezorfa** [comment]
@thepoorswiss  Thanks for replying, When I run the following commands  
 `$ git clone --recursive git://github.com/wichtounet/budgetwarrior.git 
$ cd budgetwarrior 
$ ./build_macos.sh 
$ cd build
$ make`

no `release_debug` directory is generated.

However, when you suggested to do a `sudo make install` from `budgetwarrior`, then `release_debug` is generated but with the error as mentioned in the previous comment.

**Comment by thepoorswiss** [comment]
Is there a `release_debug` directory inside `build`?

**Comment by ezorfa** [comment]
@thepoorswiss  NO. Its not there.

**Comment by wichtounet** [comment]
I really do not know enough about the build on Mac :disappointed: 

Can you do `ls -laR` inside `build` and paste the results here?

**Comment by ezorfa** [comment]
These are the results: 

`total 56
drwxr-xr-x   7 ezorfa  staff    224 Oct 12 23:23 .
drwxr-xr-x  26 ezorfa  staff    832 Oct 13 09:22 ..
-rw-r--r--@  1 ezorfa  staff  15641 Oct 12 23:22 CMakeCache.txt
drwxr-xr-x  11 ezorfa  staff    352 Oct 12 23:23 CMakeFiles
-rw-r--r--@  1 ezorfa  staff   4277 Oct 12 23:22 Makefile
-rw-r--r--   1 ezorfa  staff   1565 Oct 12 23:22 cmake_install.cmake
drwxr-xr-x   6 ezorfa  staff    192 Oct 12 23:23 src

./CMakeFiles:
total 136
drwxr-xr-x  11 ezorfa  staff    352 Oct 12 23:23 .
drwxr-xr-x   7 ezorfa  staff    224 Oct 12 23:23 ..
drwxr-xr-x   9 ezorfa  staff    288 Oct 12 23:22 3.15.3
-rw-r--r--@  1 ezorfa  staff    656 Oct 12 23:22 CMakeDirectoryInformation.cmake
-rw-r--r--   1 ezorfa  staff  34276 Oct 12 23:22 CMakeOutput.log
drwxr-xr-x   2 ezorfa  staff     64 Oct 12 23:23 CMakeTmp
-rw-r--r--@  1 ezorfa  staff   9342 Oct 12 23:22 Makefile.cmake
-rw-r--r--@  1 ezorfa  staff   3948 Oct 12 23:22 Makefile2
-rw-r--r--   1 ezorfa  staff    364 Oct 12 23:22 TargetDirectories.txt
-rw-r--r--@  1 ezorfa  staff     85 Oct 12 23:22 cmake.check_cache
-rw-r--r--@  1 ezorfa  staff      3 Oct 12 23:22 progress.marks

./CMakeFiles/3.15.3:
total 64
drwxr-xr-x   9 ezorfa  staff   288 Oct 12 23:22 .
drwxr-xr-x  11 ezorfa  staff   352 Oct 12 23:23 ..
-rw-r--r--   1 ezorfa  staff  3007 Oct 12 23:22 CMakeCCompiler.cmake
-rw-r--r--   1 ezorfa  staff  5791 Oct 12 23:22 CMakeCXXCompiler.cmake
-rwxr-xr-x   1 ezorfa  staff  4304 Oct 12 23:22 CMakeDetermineCompilerABI_C.bin
-rwxr-xr-x   1 ezorfa  staff  4288 Oct 12 23:22 CMakeDetermineCompilerABI_CXX.bin
-rw-r--r--   1 ezorfa  staff   362 Oct 12 23:22 CMakeSystem.cmake
drwxr-xr-x   5 ezorfa  staff   160 Oct 12 23:22 CompilerIdC
drwxr-xr-x   5 ezorfa  staff   160 Oct 12 23:22 CompilerIdCXX

./CMakeFiles/3.15.3/CompilerIdC:
total 64
drwxr-xr-x  5 ezorfa  staff    160 Oct 12 23:22 .
drwxr-xr-x  9 ezorfa  staff    288 Oct 12 23:22 ..
-rw-r--r--  1 ezorfa  staff  20099 Oct 12 23:22 CMakeCCompilerId.c
-rwxr-xr-x  1 ezorfa  staff   8616 Oct 12 23:22 a.out
drwxr-xr-x  2 ezorfa  staff     64 Oct 12 23:22 tmp

./CMakeFiles/3.15.3/CompilerIdC/tmp:
total 0
drwxr-xr-x  2 ezorfa  staff   64 Oct 12 23:22 .
drwxr-xr-x  5 ezorfa  staff  160 Oct 12 23:22 ..

./CMakeFiles/3.15.3/CompilerIdCXX:
total 64
drwxr-xr-x  5 ezorfa  staff    160 Oct 12 23:22 .
drwxr-xr-x  9 ezorfa  staff    288 Oct 12 23:22 ..
-rw-r--r--  1 ezorfa  staff  19635 Oct 12 23:22 CMakeCXXCompilerId.cpp
-rwxr-xr-x  1 ezorfa  staff   8600 Oct 12 23:22 a.out
drwxr-xr-x  2 ezorfa  staff     64 Oct 12 23:22 tmp

./CMakeFiles/3.15.3/CompilerIdCXX/tmp:
total 0
drwxr-xr-x  2 ezorfa  staff   64 Oct 12 23:22 .
drwxr-xr-x  5 ezorfa  staff  160 Oct 12 23:22 ..

./CMakeFiles/CMakeTmp:
total 0
drwxr-xr-x   2 ezorfa  staff   64 Oct 12 23:23 .
drwxr-xr-x  11 ezorfa  staff  352 Oct 12 23:23 ..

./src:
total 23920
drwxr-xr-x  6 ezorfa  staff       192 Oct 12 23:23 .
drwxr-xr-x  7 ezorfa  staff       224 Oct 12 23:23 ..
drwxr-xr-x  5 ezorfa  staff       160 Oct 12 23:23 CMakeFiles
-rw-r--r--@ 1 ezorfa  staff     66184 Oct 12 23:22 Makefile
-rwxr-xr-x@ 1 ezorfa  staff  12171656 Oct 12 23:23 budget
-rw-r--r--  1 ezorfa  staff       992 Oct 12 23:22 cmake_install.cmake

./src/CMakeFiles:
total 16
drwxr-xr-x   5 ezorfa  staff   160 Oct 12 23:23 .
drwxr-xr-x   6 ezorfa  staff   192 Oct 12 23:23 ..
-rw-r--r--   1 ezorfa  staff   656 Oct 12 23:22 CMakeDirectoryInformation.cmake
drwxr-xr-x  48 ezorfa  staff  1536 Oct 12 23:23 budget.dir
-rw-r--r--   1 ezorfa  staff     3 Oct 12 23:22 progress.marks

./src/CMakeFiles/budget.dir:
total 34848
drwxr-xr-x  48 ezorfa  staff     1536 Oct 12 23:23 .
drwxr-xr-x   5 ezorfa  staff      160 Oct 12 23:23 ..
-rw-r--r--   1 ezorfa  staff    52973 Oct 12 23:22 CXX.includecache
-rw-r--r--   1 ezorfa  staff    10409 Oct 12 23:22 DependInfo.cmake
-rw-r--r--   1 ezorfa  staff   388784 Oct 12 23:23 accounts.cpp.o
drwxr-xr-x  13 ezorfa  staff      416 Oct 12 23:23 api
-rw-r--r--   1 ezorfa  staff  1437272 Oct 12 23:23 api.cpp.o
-rw-r--r--   1 ezorfa  staff    47604 Oct 12 23:22 args.cpp.o
-rw-r--r--   1 ezorfa  staff   497228 Oct 12 23:23 assets.cpp.o
-rw-r--r--   1 ezorfa  staff   233632 Oct 12 23:22 budget.cpp.o
-rw-r--r--   1 ezorfa  staff     6992 Oct 12 23:22 budget_exception.cpp.o
-rw-r--r--   1 ezorfa  staff   116852 Oct 12 23:22 build.make
-rw-r--r--   1 ezorfa  staff     3089 Oct 12 23:22 cmake_clean.cmake
-rw-r--r--   1 ezorfa  staff    53612 Oct 12 23:22 compute.cpp.o
-rw-r--r--   1 ezorfa  staff   219496 Oct 12 23:22 config.cpp.o
-rw-r--r--   1 ezorfa  staff    88820 Oct 12 23:22 console.cpp.o
-rw-r--r--   1 ezorfa  staff   128112 Oct 12 23:22 console_writer.cpp.o
-rw-r--r--   1 ezorfa  staff  1497516 Oct 12 23:23 currency.cpp.o
-rw-r--r--   1 ezorfa  staff    59984 Oct 12 23:22 date.cpp.o
-rw-r--r--   1 ezorfa  staff   267428 Oct 12 23:22 debts.cpp.o
-rw-r--r--   1 ezorfa  staff    99084 Oct 12 23:22 depend.internal
-rw-r--r--   1 ezorfa  staff   209541 Oct 12 23:22 depend.make
-rw-r--r--   1 ezorfa  staff   293184 Oct 12 23:22 earnings.cpp.o
-rw-r--r--   1 ezorfa  staff   311892 Oct 12 23:22 expenses.cpp.o
-rw-r--r--   1 ezorfa  staff      520 Oct 12 23:22 flags.make
-rw-r--r--   1 ezorfa  staff   293936 Oct 12 23:22 fortune.cpp.o
-rw-r--r--   1 ezorfa  staff   160600 Oct 12 23:22 gc.cpp.o
-rw-r--r--   1 ezorfa  staff     2876 Oct 12 23:22 guid.cpp.o
-rw-r--r--   1 ezorfa  staff    21888 Oct 12 23:22 help.cpp.o
-rw-r--r--   1 ezorfa  staff   213952 Oct 12 23:22 html_writer.cpp.o
-rw-r--r--   1 ezorfa  staff   269096 Oct 12 23:22 incomes.cpp.o
-rw-r--r--   1 ezorfa  staff     2988 Oct 12 23:22 link.txt
-rw-r--r--   1 ezorfa  staff    69376 Oct 12 23:22 money.cpp.o
-rw-r--r--   1 ezorfa  staff   293584 Oct 12 23:22 objectives.cpp.o
-rw-r--r--   1 ezorfa  staff   742676 Oct 12 23:23 overview.cpp.o
drwxr-xr-x  20 ezorfa  staff      640 Oct 12 23:23 pages
-rw-r--r--   1 ezorfa  staff   135648 Oct 12 23:22 predict.cpp.o
-rw-r--r--   1 ezorfa  staff     1478 Oct 12 23:22 progress.make
-rw-r--r--   1 ezorfa  staff   291244 Oct 12 23:22 recurring.cpp.o
-rw-r--r--   1 ezorfa  staff   200972 Oct 12 23:22 report.cpp.o
-rw-r--r--   1 ezorfa  staff   182976 Oct 12 23:22 retirement.cpp.o
-rw-r--r--   1 ezorfa  staff  1619072 Oct 12 23:23 server.cpp.o
-rw-r--r--   1 ezorfa  staff  1510612 Oct 12 23:23 share.cpp.o
-rw-r--r--   1 ezorfa  staff   245752 Oct 12 23:22 summary.cpp.o
-rw-r--r--   1 ezorfa  staff   103812 Oct 12 23:22 utils.cpp.o
-rw-r--r--   1 ezorfa  staff    15732 Oct 12 23:22 version.cpp.o
-rw-r--r--   1 ezorfa  staff    53448 Oct 12 23:22 versioning.cpp.o
-rw-r--r--   1 ezorfa  staff   310148 Oct 12 23:22 wishes.cpp.o

./src/CMakeFiles/budget.dir/api:
total 52888
drwxr-xr-x  13 ezorfa  staff      416 Oct 12 23:23 .
drwxr-xr-x  48 ezorfa  staff     1536 Oct 12 23:23 ..
-rw-r--r--   1 ezorfa  staff  1415704 Oct 12 23:23 accounts_api.cpp.o
-rw-r--r--   1 ezorfa  staff  1438272 Oct 12 23:23 assets_api.cpp.o
-rw-r--r--   1 ezorfa  staff  1398272 Oct 12 23:23 debts_api.cpp.o
-rw-r--r--   1 ezorfa  staff  1411184 Oct 12 23:23 earnings_api.cpp.o
-rw-r--r--   1 ezorfa  staff  1415464 Oct 12 23:23 expenses_api.cpp.o
-rw-r--r--   1 ezorfa  staff  1397436 Oct 12 23:23 fortunes_api.cpp.o
-rw-r--r--   1 ezorfa  staff  1408096 Oct 12 23:23 incomes_api.cpp.o
-rw-r--r--   1 ezorfa  staff  1411588 Oct 12 23:23 objectives_api.cpp.o
-rw-r--r--   1 ezorfa  staff  1397824 Oct 12 23:23 recurrings_api.cpp.o
-rw-r--r--   1 ezorfa  staff  1474060 Oct 12 23:23 server_api.cpp.o
-rw-r--r--   1 ezorfa  staff  1399412 Oct 12 23:23 wishes_api.cpp.o

./src/CMakeFiles/budget.dir/pages:
total 86456
drwxr-xr-x  20 ezorfa  staff      640 Oct 12 23:23 .
drwxr-xr-x  48 ezorfa  staff     1536 Oct 12 23:23 ..
-rw-r--r--   1 ezorfa  staff  1395500 Oct 12 23:23 accounts_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1408344 Oct 12 23:23 asset_shares_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1458496 Oct 12 23:23 asset_values_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1398564 Oct 12 23:23 assets_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1407104 Oct 12 23:23 debts_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1487256 Oct 12 23:23 earnings_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1534300 Oct 12 23:23 expenses_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1442272 Oct 12 23:23 fortunes_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1380140 Oct 12 23:23 incomes_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1434380 Oct 12 23:23 index_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1580132 Oct 12 23:23 net_worth_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1427472 Oct 12 23:23 objectives_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1428400 Oct 12 23:23 overview_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1391736 Oct 12 23:23 recurrings_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1378680 Oct 12 23:23 report_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1410556 Oct 12 23:23 retirement_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1622580 Oct 12 23:23 server_pages.cpp.o
-rw-r--r--   1 ezorfa  staff  1409324 Oct 12 23:23 wishes_pages.cpp.o`

**Comment by wichtounet** [comment]
The execute seems to be `build/src/budget`

You can try to execute it

`./build/src/budget`

And if you want to install, you should be able to do something like: 

`sudo cp build/src/budget /usr/local/bin/budget`

**Comment by ezorfa** [comment]
@wichtounet 

When I did `./build/src/budget` , 

I get the following, but the execute doesnt persist to add any accounts 👍

`ezorfa@ezorfa-MacBook-Pro budgetwarrior % ./build/src/budget 
No accounts defined, you should start by defining some of them
ezorfa@ezorfa-MacBook-Pro budgetwarrior % `

**Comment by wichtounet** [comment]
Ok, now we are getting somewhere :)

I would recommend you read the start tutorial: https://github.com/wichtounet/budgetwarrior/wiki/Start-tutorial

This will tell you how can you get started to create accounts and such. 

Since this first issue is now resolved, I will close it. Feel free to open a new one if you have any other issue :)

**Comment by ezorfa** [comment]
Thankyou! It worked. Your project is very nice, especially the web interface!
