### ISSUE TITLE
Understanding the design

### ISSUE THREAD

**Issue by ezorfa** [wichtounet/budgetwarrior#15]
Hi @wichtounet !

First of all, Thankyou for the great tool. 

I was trying to understand your code and how it is designed. It is little complicated to understand. I was just wondering if you have any block diagram / or any pointers to design patterns on which the design of this system is based.

Any help would be great. Thankyou once again.

**Comment by thepoorswiss** [comment]
Hi @ezorfa 

I am afraid I have nothing of that sort. 
On the other hand, even if there is a lot of code, it's not that complicated to some other projects. 

What part are you interested in? The command line part or the web interface?
I can give you a few pointers of how it works. It's mostly simple.

**Comment by ezorfa** [comment]
Thankyou @thepoorswiss ,

I am interested in both and would basically wanted to understand the design part. As i understand, its not object-oriented programming, but more of functional programming, I believe. 

However, I have no specific question as yet, therefore, will come back to you with much more intellectual doubts.

**Comment by thepoorswiss** [comment]
Here are a few pointers: 
* The code is separated into modules: expenses, earnings, debts, assets, ...
* Each module is responsible for his command-line options and managing its data
* Data is stored in simple text files with a  custom format
* In command-line mode, the data is loaded at the beginning and saved at the end
* In server mode (web), the data is loaded at the beginning and then saved after each update
* In the server implementation, there are two important parts:
    * The pages which are the views of the interfaces
    * The API which are the actions of the interfaces

If you want to learn about his code, get started with a simple module, like expenses or earnings and check its code

**Comment by wichtounet** [comment]
Here are a few pointers:

The code is separated into modules: expenses, earnings, debts, assets, ...
Each module is responsible for his command-line options and managing its data
Data is stored in simple text files with a custom format
In command-line mode, the data is loaded at the beginning and saved at the end
In server mode (web), the data is loaded at the beginning and then saved after each update
In the server implementation, there are two important parts:
The pages which are the views of the interfaces
The API which are the actions of the interfaces
If you want to learn about his code, get started with a simple module, like expenses or earnings and check its code

**Comment by ezorfa** [comment]
Hi @wichtounet ! Thankyou. This certainly helped!
