### ISSUE TITLE
Could not make install on Linux 20.04 LTS

### ISSUE THREAD

**Issue by j-hmd** [wichtounet/budgetwarrior#16]
Hi, I'm new to this and I installed the following:
- `libssl-dev`
- `uuid-dev`
- `uuid-runtime`

Then performed `make` apparently successfully, and I have the "budget" in the bin folder.

This is the code error:
```
Installation of budgetwarrior
=============================

install budget.man /usr/local/share/man/man3/budget.3
install: cannot create regular file '/usr/local/share/man/man3/budget.3': No such file or directory
make: *** [Makefile:41: install] Error 1
```
Thank you!

**Comment by wichtounet** [comment]
Hi, 

Sorry about that. It must because the directories are different on your distributions. You can try again now with the latest version. I have disabled the installation of the man pages by default. They are grossly outdated anyway. 

If this does not work, you can try change the prefix:

```
prefix=/usr/ make install
```

**Comment by j-hmd** [comment]
No worries at all. It worked thank you!

**Comment by wichtounet** [comment]
Cool!

Let me know you have any other issues. This software has not been tested much except by me.
