### ISSUE TITLE
XDG Base Directory compliance

### ISSUE THREAD

**Issue by hiimmill** [wichtounet/budgetwarrior#18]
Hi there, are you planning on introducing XDG Base Directory compliance? 
What I'm interested in is having budgetwarrior search for config also in ~/.config/ and for data in ~/.local/share/ as proposed by the Free Desktop standard. 
Reading:
https://wiki.archlinux.org/index.php/XDG_Base_Directory
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by wichtounet** [comment]
Hi, 

No, it's not planned. I will add this to my list of tasks for this project, but I am not planning to make this a priority.

**Comment by xerus2000** [comment]
I would like to second this issue. I don't understand why you closed it, considering that it is open. I was about to open a similar issue as well ^^
