### ISSUE TITLE
Build for MacOS is not working

### ISSUE THREAD

**Issue by ljubomirsinadinovski** [wichtounet/budgetwarrior#24]
This is the terminal output when running ./build_macos.sh:

https://pastebin.com/tZrzf3pe

(I added pastebin link because output was too long for github)

**Comment by wichtounet** [comment]
Hi

FYI, the Mac OS building code is highly experimental, I have never tested it and it was contributed by @robromano 

Looking at the errors, I can see two things: 
* It looks like the loguru submodule is missing. Can you do a `git submodule update --init --recursive`?
* It looks like there are C++17 warnings and issues, can you try replace this line in Cmakelists.txt

`set(CMAKE_CXX_STANDARD 14)`

by

`set(CMAKE_CXX_STANDARD 14)`

**Comment by ljubomirsinadinovski** [comment]
I changed the CMAKE_CXX_STANDARD, but i still have problems with installing loguru. I have also tried this solution:

`
git submodule update --init --recursive
Then, try the pull --recurse-submodules=true again.

Somehow, [activating the traces](https://stackoverflow.com/a/56094711/6309) improve the situation:

git -c trace2.eventTarget=1 pull --recurse-submodules=true
`

Source: https://stackoverflow.com/questions/64190258/git-submodule-fails-with-could-not-access-submodule

**Comment by ljubomirsinadinovski** [comment]
I also tried doing change in the .gitmodules file by replacing the https into the ssh path of the project:

```
[submodule "loguru"]
	path = loguru
	url = git@github.com:emilk/loguru.git
```

Still not working..

Then I tried:

```
git submodules deinit loguru
git submodule update loguru
git submodule init loguru  
git submodule sync loguru
git submodule set-url loguru git@github.com:emilk/loguru.git
git git submodule update --init --force -    
```

**Comment by robromano** [comment]
I have not been maintaining the CMakeLists.txt for this project.

When a new package is added, we need to update CMakeLists.txt accordingly.
For loguru and possibly others, for example, add the requisite
include_directories() statement.  Some packages have native CMake support
so you can do find_packages() for those.

Try this diff:

$ git diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c6cb4c2..68af89b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -12,6 +12,7 @@ find_package(OpenSSL REQUIRED)

 include_directories(include)
 include_directories(cpp-httplib)
+include_directories(loguru)
 include_directories(${OPENSSL_INCLUDE_DIR})

 add_subdirectory(src)

**Comment by robromano** [comment]
The current error I see after setting C++ to 17 is

budgetwarrior/include/cpp_utils/string.hpp:18:72: error: no member named
'ptr_fun' in namespace 'std'
    s.erase(s.begin(), std::find_if(s.begin(), s.end(),
std::not1(std::ptr_fun<int, int>(std::isspace))));

std::ptr_fun was a C++11 feature and fully removed from C++17.

**Comment by robromano** [comment]
https://github.com/wichtounet/budgetwarrior/pull/25 for fixing up all issues.

**Comment by robromano** [comment]
https://github.com/wichtounet/cpp_utils/pull/1 for cpp_utils fix needed.

**Comment by wichtounet** [comment]
Thanks @robromano, we can discuss in your two PRs

**Comment by robromano** [comment]
I just converted a repo of mine using Travis CI (which is now unsupported) to Github Actions - to automatically build and test all changes on push.  Github Actions are fantastic.

I'd propose converting away from Makefile to CMake, and enable Github Actions workflow to build both platforms every push. I'll submit a PR.

Working example of CMake on Linux for budgetwarrior:  https://github.com/robromano/budgetwarrior/runs/7660441303?check_suite_focus=true
(It probably used a newer version of GCC - which is why there are some new compiler errors there)

**Comment by ljubomirsinadinovski** [comment]
@robromano how do i download the build? I don't see any artefact do download or anything, only logs

**Comment by robromano** [comment]
You will still need to build it yourself, the GitHub action workflow is
just to verify future code submissions will build successfully with both
compilers/platforms.
