### ISSUE TITLE
Extra double quote in bash completion file

### ISSUE THREAD

**Issue by billux** [wichtounet/budgetwarrior#3]
Hi,

There is an extra double at the end of line 4 of bash completion file, raising a syntax error.

**Comment by billux** [comment]
And there is a small typo making bash completion fail. The correct line should be:

`    local cur=${COMP_WORDS[COMP_CWORD]}
`

**Comment by wichtounet** [comment]
Hi, 

Thank you very much for bringing this to my attention. You're absolutely right. This should be fixed by the mentioned commit above.
