### ISSUE TITLE
Extend the list of possible recurrence types

### ISSUE THREAD

**Issue by nattomi** [wichtounet/budgetwarrior#35]
Would the current architecture easily allow the addition of more recurrence types such as quarterly, annual, biannual?

**Comment by wichtounet** [comment]
Yes, quarterly, yearly, and bi-yearly are easy additions. 

Would they be useful to you?

**Comment by nattomi** [comment]
Definitely, because I do have a couple of expenses with the above mentioned frequencies. It would be of great help if you could invest the time.

**Comment by wichtounet** [comment]
It seems to me like it's a good idea, I will plan to add these three features soon. 

I have added yearly already in ed7922cb84e1d272468da1d61480bb2d8f341050, so it should be fairly easy to implement the others.

**Comment by wichtounet** [comment]
I have now added bi-yearly and quarterly, you should have everything you need 👍

**Comment by nattomi** [comment]
I have tested the `budget add` command and can confirm that now it supports the bi-yearly and quarterly modes. Thank you for the quick reaction.

**Comment by wichtounet** [comment]
I am glad it works for you 👍
