### ISSUE TITLE
fatal error: 'openssl/ssl.h' file not found

### ISSUE THREAD

**Issue by ferologics** [wichtounet/budgetwarrior#5]
Hey, I followed the install instructions up to the `make` and got this: `fatal error: 'openssl/ssl.h' file not found`

Full log ⚠️:
```
~/P/budgetwarrior> make
-e [release_debug] Compile src/accounts.cpp
src/accounts.cpp:464:12: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
    return std::move(accounts);
           ^
src/accounts.cpp:464:12: note: remove std::move call here
    return std::move(accounts);
           ^~~~~~~~~~        ~
1 warning generated.
-e [release_debug] Compile src/api.cpp
In file included from src/api.cpp:17:
In file included from include/http.hpp:12:
cpp-httplib/httplib.h:63:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [release_debug/src/api.cpp.o] Error 1
~/P/budgetwarrior>
```

Any idea what I need to change on my computer?

**Comment by mbrucher** [comment]
Do you have openSSL installed?

**Comment by wichtounet** [comment]
Hi @ferologics, 

As @mbrucher pointed out, you need openssl. 

If you are on Ubuntu for instance, you need to install openssl-devel. 
On what platform are you ?

**Comment by ferologics** [comment]
Hey, I'm on macOS Mojave beta and `brew install openssl` says that `openssl 1.0.2p is already installed and up-to-date`.

**Comment by ferologics** [comment]
Checking how to install the dev version via Homebrew now

**Comment by ferologics** [comment]
In Homebrew the `devel` is included with the `openssl` package, perhaps I have to link it again.

**Comment by wichtounet** [comment]
Apparently, there is something special about openssl on macos. 

You can try to link it if you didn't do it again, but it may fail. Look at this article: https://medium.com/@timmykko/using-openssl-library-with-macos-sierra-7807cfd47892

It suggests doing the following command: 

`ln -s /usr/local/opt/openssl/include/openssl /usr/local/include`

**Comment by ferologics** [comment]
The link worked on the previous error. 
Now I get `implicit instantiation of undefined template 'std::__1::array<int, 5>'`

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/5576161/44949365-2065b600-ae30-11e8-9d19-37acbb2f47c3.png">

I ran `make` on both Xcode and latest beta.
```
$ cpp --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ sudo xcode-select --switch /Applications/Xcode-beta.app/Contents/Developer/
Password:
$ cpp --version
Apple LLVM version 10.0.0 (clang-1000.10.43.1)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

macOS Mojave 
Version `10.14 Beta (18A365a)`

**Comment by wichtounet** [comment]
I made a small change in the code. Could you update your repository (git pull) and try make again ?

**Comment by ferologics** [comment]
As well as the `bash` completion install directory to `/usr/local/etc/bash_completion.d/budget` 👉 `$(prefix)/etc/bash_completion.d/budget`.
