### ISSUE TITLE
Access denied on install to SIP protected directory

### ISSUE THREAD

**Issue by ferologics** [wichtounet/budgetwarrior#7]
The `$ sudo make install` command is exiting with an error with `install: /usr/bin/budget: Operation not permitted`. 

Since `macOS El Capitan` (bye bye OS X) we have System Integrity Protection ([SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection)) aka rootless. The relevant part of SIP here is:

> System Integrity Protection protects system files and directories that are flagged for protection. This happens either by adding an extended file attribute to a file or directory, by adding the file or directory to /System/Library/Security/rootless.conf or both. Among the protected directories are: /System, /bin, /sbin, /usr (but not /usr/local).

If it is impossible to modify `/usr`, but not `/usr/local`, then the prefix should be set to `/usr/local`?

**Comment by ferologics** [comment]
The `bash` completion install directory does not exist on macOS at it's specified path `/etc/bash_completion.d`. It lives in `/usr/local/etc/bash_completion.d/` 

👉 The final install path should then be `$(prefix)/etc/bash_completion.d/budget`.

**Comment by wichtounet** [comment]
I had no idea about this SIP. I don't use Mac OS X and this was never tested on it. 

I merged #6, can you confirm if this is fixed ?
